### WINGS의 Integration Daily on the book by Hotel 활용

In [1]:
import pandas as pd

In [2]:
yy = ['2003']
mm = ['07','08','09','10','11','12']

In [3]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [4]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [6]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [7]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [8]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [9]:
data.columns = new_col

In [10]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2003-12-28,Sun,89.0,1.0,46.0,51.7,"107,272","4,934,493",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2003-12-29,Mon,85.0,5.0,66.0,77.6,"84,144","5,553,508",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2003-12-30,Tue,89.0,1.0,58.0,65.2,"84,436","4,897,312",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2003-12-31,Wed,89.0,1.0,80.0,89.9,"100,984","8,078,751",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Total,,2745.0,45.0,1230.0,44.8,88670,109064087,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
data2003 = data[data['Date']!= 'Total']
data2003

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2003-12-27,Sat,88.0,2.0,56.0,63.6,"83,378","4,669,144",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2003-12-28,Sun,89.0,1.0,46.0,51.7,"107,272","4,934,493",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2003-12-29,Mon,85.0,5.0,66.0,77.6,"84,144","5,553,508",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2003-12-30,Tue,89.0,1.0,58.0,65.2,"84,436","4,897,312",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2003-12-31,Wed,89.0,1.0,80.0,89.9,"100,984","8,078,751",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ----------------------------------------------------------------------------------------------------

In [12]:
yy = ['2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020']
mm = ['01','02','03','04','05','06','07','08','09','10','11','12']

In [13]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [14]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2004-01-01,Thu,89,1,68,76.4,"114,383","7,778,018",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-02,Fri,89,1,79,88.8,"119,379","9,430,924",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-03,Sat,89,1,55,61.8,"111,780","6,147,881",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-04,Sun,89,1,45,50.6,"102,855","4,628,476",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-05,Mon,89,1,43,48.3,"77,579","3,335,906",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [16]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [17]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [18]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [19]:
data.columns = new_col

In [20]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2004-01-01,Thu,89,1,68,76.4,"114,383","7,778,018",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-02,Fri,89,1,79,88.8,"119,379","9,430,924",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-03,Sat,89,1,55,61.8,"111,780","6,147,881",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-04,Sun,89,1,45,50.6,"102,855","4,628,476",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-05,Mon,89,1,43,48.3,"77,579","3,335,906",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2020-12-28,Mon,92,0,27,29.3,"153,094","4,133,542","460,544",46.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
28,2020-12-29,Tue,92,0,23,25.0,"164,784","3,790,030","180,181",37.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
29,2020-12-30,Wed,92,0,20,21.7,"193,526","3,870,529","268,226",47.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
30,2020-12-31,Thu,92,0,24,26.1,"213,515","5,124,361","648,634",50.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
31,Total,,2850,2,1135,39.8,154309,175141026,20999995,1740.0,...,114269,7656000,0,2325.0,0.0,1220.0,52.5,122945,149993100,0

In [21]:
data_past = data[data['Date']!= 'Total']
data_past

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2004-01-01,Thu,89,1,68,76.4,"114,383","7,778,018",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-02,Fri,89,1,79,88.8,"119,379","9,430,924",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-03,Sat,89,1,55,61.8,"111,780","6,147,881",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-04,Sun,89,1,45,50.6,"102,855","4,628,476",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-05,Mon,89,1,43,48.3,"77,579","3,335,906",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2020-12-27,Sun,92,0,25,27.2,"153,063","3,826,575","705,816",51.0,...,0,"232,000",0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
27,2020-12-28,Mon,92,0,27,29.3,"153,094","4,133,542","460,544",46.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
28,2020-12-29,Tue,92,0,23,25.0,"164,784","3,790,030","180,181",37.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
29,2020-12-30,Wed,92,0,20,21.7,"193,526","3,870,529","268,226",47.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
30,2020-12-31,Thu,92,0,24,26.1,"213,515","5,124,361","648,634",50.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0

## ----------------------------------------------------------------------------------------------------

In [22]:
yy = ['2021']
mm = ['01','02','03','04','05','06','07','08','09','10','11','12']

In [23]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [24]:
data = data.loc[:, :'FB Rev..6']

In [25]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2021-01-01,Fri,92,0,27,29.3,"223,941","6,046,409","797,996",49,...,0,0,0,75,0,0,0.0,0,0,0
1,2021-01-02,Sat,92,0,25,27.2,"195,915","4,897,872","690,224",56,...,0,0,0,75,0,0,0.0,0,0,0
2,2021-01-03,Sun,92,0,15,16.3,"145,439","2,181,590","339,953",57,...,0,0,0,75,0,0,0.0,0,0,0
3,2021-01-04,Mon,92,0,4,4.3,"171,741","686,964","74,727",55,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
4,2021-01-05,Tue,92,0,13,14.1,"130,035","1,690,454","205,639",56,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0

In [26]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [27]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [28]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [29]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [30]:
data.columns = new_col

In [31]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2021-01-01,Fri,92,0,27,29.3,"223,941","6,046,409","797,996",49,...,0,0,0,75,0,0,0.0,0,0,0
1,2021-01-02,Sat,92,0,25,27.2,"195,915","4,897,872","690,224",56,...,0,0,0,75,0,0,0.0,0,0,0
2,2021-01-03,Sun,92,0,15,16.3,"145,439","2,181,590","339,953",57,...,0,0,0,75,0,0,0.0,0,0,0
3,2021-01-04,Mon,92,0,4,4.3,"171,741","686,964","74,727",55,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
4,2021-01-05,Tue,92,0,13,14.1,"130,035","1,690,454","205,639",56,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2021-12-28,Tue,92,0,80,87.0,"186,346","14,907,652","1,820,130",59,...,0,0,0,75,0,0,0.0,0,"-1,276,364",0
28,2021-12-29,Wed,92,0,70,76.1,"187,618","13,133,251","1,546,357",59,...,0,0,0,75,0,0,0.0,0,0,0
29,2021-12-30,Thu,92,0,76,82.6,"215,450","16,374,173","1,657,450",59,...,0,0,0,75,0,0,0.0,0,0,0
30,2021-12-31,Fri,91,1,81,89.0,"295,308","23,919,912","1,808,406",59,...,0,0,0,75,0,0,0.0,0,0,0
31,Total,,2842,7,2226,78.3,191813,426975887,42986096,1785,...,53889,1455000,0,2325,0,576,24.8,47898,27589143,0

In [32]:
data2021 = data[data['Date']!= 'Total']
data2021

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2021-01-01,Fri,92,0,27,29.3,"223,941","6,046,409","797,996",49,...,0,0,0,75,0,0,0.0,0,0,0
1,2021-01-02,Sat,92,0,25,27.2,"195,915","4,897,872","690,224",56,...,0,0,0,75,0,0,0.0,0,0,0
2,2021-01-03,Sun,92,0,15,16.3,"145,439","2,181,590","339,953",57,...,0,0,0,75,0,0,0.0,0,0,0
3,2021-01-04,Mon,92,0,4,4.3,"171,741","686,964","74,727",55,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
4,2021-01-05,Tue,92,0,13,14.1,"130,035","1,690,454","205,639",56,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2021-12-27,Mon,90,0,72,80.0,"187,317","13,486,841","1,623,721",59,...,0,0,0,75,0,0,0.0,0,0,0
27,2021-12-28,Tue,92,0,80,87.0,"186,346","14,907,652","1,820,130",59,...,0,0,0,75,0,0,0.0,0,"-1,276,364",0
28,2021-12-29,Wed,92,0,70,76.1,"187,618","13,133,251","1,546,357",59,...,0,0,0,75,0,0,0.0,0,0,0
29,2021-12-30,Thu,92,0,76,82.6,"215,450","16,374,173","1,657,450",59,...,0,0,0,75,0,0,0.0,0,0,0
30,2021-12-31,Fri,91,1,81,89.0,"295,308","23,919,912","1,808,406",59,...,0,0,0,75,0,0,0.0,0,0,0

## ----------------------------------------------------------------------------------------------------

In [33]:
yy = ['2022']
mm = ['01', '02']

In [34]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [35]:
data = data.loc[:, :'FB Rev..6']

In [36]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2022-01-01,Sat,91,1,75,82.4,"254,748","19,106,127","2,039,406",59,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-01-02,Sun,92,0,57,62.0,"178,332","10,164,911","1,238,268",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-01-03,Mon,92,0,61,66.3,"163,256","9,958,637","1,038,132",54,...,0,0,0,75,0,0,0.0,0,0,0
3,2022-01-04,Tue,92,0,57,62.0,"156,772","8,936,010","1,419,221",56,...,0,0,0,75,0,0,0.0,0,0,0
4,2022-01-05,Wed,92,0,61,66.3,"161,997","9,881,790","1,379,541",56,...,0,0,0,75,0,0,0.0,0,0,0

In [37]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [38]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [39]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [40]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [41]:
data.columns = new_col

In [42]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2022-01-01,Sat,91,1,75,82.4,"254,748","19,106,127","2,039,406",59,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-01-02,Sun,92,0,57,62.0,"178,332","10,164,911","1,238,268",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-01-03,Mon,92,0,61,66.3,"163,256","9,958,637","1,038,132",54,...,0,0,0,75,0,0,0.0,0,0,0
3,2022-01-04,Tue,92,0,57,62.0,"156,772","8,936,010","1,419,221",56,...,0,0,0,75,0,0,0.0,0,0,0
4,2022-01-05,Wed,92,0,61,66.3,"161,997","9,881,790","1,379,541",56,...,0,0,0,75,0,0,0.0,0,0,0
5,2022-01-06,Thu,92,0,66,71.7,"171,070","11,290,647","1,530,542",58,...,0,0,0,75,0,0,0.0,0,0,0
6,2022-01-07,Fri,92,0,68,73.9,"196,679","13,374,199","1,654,766",57,...,0,0,0,75,0,0,0.0,0,0,0
7,2022-01-08,Sat,92,0,69,75.0,"198,507","13,696,957","1,560,266",57,...,"50,000","1,700,000",0,75,0,47,62.7,"64,875","3,049,105",0
8,2022-01-09,Sun,92,0,67,72.8,"185,547","12,431,677","1,691,677",56,...,0,0,0,75,0,0,0.0,0,0,0
9,2022-01-10,Mon,92,0,64,69.6,"178,001","11,392,066","1,543,902",58,...,0,0,0,75,0,0,0.0,0,0,0
10,2022-01-11,Tue,92,0,62,67.4,"171,622","10,640,542","1,471,768",58,...,"600,000","2,400,000",0,75,0,0,0.0,0,"136,545",0
11,2022-01-12,Wed,92,0,72,78.3,"172,053","12,387,851","1,626,088",59,...,0,0,0,75,0,0,0.0,0,0,0
12,2022-01-13,Thu,92,0,74,80.4,"167,794","12,416,740","1,388,585",59,...,0,0,0,75,0,0,0.0,0,0,0
13,2022-01-14,Fri,92,0,67,72.8,"204,640","13,710,907","2,138,992",59,...,"90,000","1,530,000",0,75,0,0,0.0,0,0,0
14,2022-01-15,Sat,92,0,77,83.7,"216,467","16,667,978","2,238,992",59,...,"122,718","4,786,000",0,75,0,41,54.7,"51,761","2,122,199",0
15,2022-01-16,Sun,92,0,69,75.0,"174,344","12,029,728","1,586,586",59,...,0,0,0,75,0,0,0.0,0,0,0
16,2022-01-17,Mon,92,0,83,90.2,"175,810","14,592,248","1,847,721",59,...,0,0,0,75,0,0,0.0,0,0,0
17,2022-01-18,Tue,92,0,83,90.2,"172,662","14,330,976","1,886,403",57,...,0,0,0,75,0,8,10.7,"150,000","1,200,000",0
18,2022-01-19,Wed,92,0,71,77.2,"166,488","11,820,653","1,557,314",58,...,0,0,0,75,0,0,0.0,0,0,0
19,2022-01-20,Thu,92,0,66,71.7,"179,120","11,821,928","1,448,269",57,...,0,0,0,75,0,0,0.0,0,0,0
20,2022-01-21,Fri,92,0,62,67.4,"212,648","13,184,170","1,710,630",56,...,"450,000","900,000",0,75,0,0,0.0,0,0,0
21,2022-01-22,Sat,92,0,67,72.8,"215,081","14,410,395","2,193,857",56,...,"117,368","2,230,000",0,75,0,40,53.3,"52,410","2,096,380",0
22,2022-01-23,Sun,92,0,75,81.5,"167,131","12,534,853","1,747,174",56,...,0,0,0,75,0,0,0.0,0,0,0
23,2022-01-24,Mon,91,0,70,76.9,"172,137","12,049,617","1,733,087",59,...,"100,000","400,000",0,75,0,0,0.0,0,0,0
24,2022-01-25,Tue,92,0,69,75.0,"172,361","11,892,888","1,718,724",57,...,0,0,0,75,0,73,97.3,"46,230","3,374,760",0
25,2022-01-26,Wed,92,0,58,63.0,"168,596","9,778,585","1,326,995",56,...,0,0,0,75,0,71,94.7,"45,680","3,243,305",0
26,2022-01-27,Thu,92,0,67,72.8,"161,864","10,844,920","1,487,131",56,...,0,0,0,75,0,67,89.3,"45,455","3,045,485",0
27,2022-01-28,Fri,92,0,70,76.1,"189,729","13,281,049","1,238,859",56,...,0,0,0,75,0,70,93.3,"43,507","3,045,486",0
28,2022-01-29,Sat,92,0,72,78.3,"242,407","17,453,268","1,363,723",54,...,0,0,0,75,0,67,89.3,"74,709","5,005,485",0
29,2022-01-30,Sun,92,0,81,88.0,"285,609","23,134,309","1,808,448",53,...,"700,000","2,100,000",0,75,0,0,0.0,0,0,0
30,2022-01-31,Mon,91,1,82,90.1,"286,506","23,493,466","2,490,540",53,...,0,0,0,75,0,0,0.0,0,0,0
31,Total,,2849,2,2142,75.2,192675,412710092,51105607,1765,...,125359,16046000,0,2325,0,484,20.8,54378,26318750,0
0,2022-02-01,Tue,92,0,68,73.9,"246,284","16,747,307","1,538,222",58,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-02-02,Wed,92,0,66,71.7,"196,848","12,991,941","1,386,540",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-02-03,Thu,92,0,77,83.7,"206,959","15,935,842","1,243,858",58,...,0,0,0,75,0,23,30.7,"55,305","1,272,009",0
3,2022-02-04,Fri,92,0,74,80.4,"196,055","14,508,091","1,716,402",59,...,0,0,0,75,0,37,49.3,"164,364","6,081,461",0
4,2022-02-05,Sat,92,0,75,81.5,"188,665","14,149,912","1,563,675",59,...,"91,629","3,207,000",0,75,0,29,38.7,"73,348","2,127,103",0
5,2022-02-06,Sun,91,1,59,64.8,"174,951","10,322,080","1,422,951",59,...,0,0,0,75,0,8,10.7,"110,364","882,912",0
6,2022-02-07,Mon,91,1,66,72.5,"179,314","11,834,730","1,673,448",59,...,"79,000","316,000",0,75,0,0,0.0,0,0,0
7,2022-02-08,Tue,92,0,60,65.2,"172,458","10,347,467","1,492,675",59,...,0,0,0,75,0,13,17.3,"52,182","678,369",0
8,2022-02-09,Wed,92,0,59,64.1,"168,592","9,946,929","1,230,130",59,...,0,0,0,75,0,0,0.0,0,"680,000",0
9,2022-02-10,Thu,92,0,59,64.1,"172,641","10,185,827","1,355,632",58,...,0,0,0,75,0,12,16.0,"100,000","1,200,000",0
10,2022-02-11,Fri,92,0,76,82.6,"200,052","15,203,914","1,811,630",57,...,"190,429","1,333,000",0,75,0,52,69.3,"100,000","5,200,000",0
11,2022-02-12,Sat,92,0,73,79.3,"205,803","15,023,647","1,818,947",59,...,"122,333","1,835,000",0,75,0,32,42.7,"102,353","3,275,282",0
12,2022-02-13,Sun,92,0,61,66.3,"179,520","10,950,690","1,144,494",59,...,0,0,0,75,0,0,0.0,0,0,0
13,2022-02-14,Mon,92,0,63,68.5,"177,834","11,203,554","1,471,220",58,...,"79,000","474,000",0,75,0,16,21.3,"100,000","1,600,000",0
14,2022-02-15,Tue,92,0,73,79.3,"167,643","12,237,906","1,529,833",59,...,0,0,0,75,0,0,0.0,0,0,0
15,2022-02-16,Wed,92,0,79,85.9,"176,436","13,938,440","1,820,719",59,...,0,0,0,75,0,0,0.0,0,0,0
16,2022-02-17,Thu,92,0,77,83.7,"181,530","13,977,772","1,927,629",59,...,0,0,0,75,0,0,0.0,0,0,0
17,2022-02-18,Fri,92,0,82,89.1,"199,937","16,394,814","1,998,493",59,...,0,0,0,75,0,0,0.0,0,0,0
18,2022-02-19,Sat,92,0,87,94.6,"195,250","16,986,738","1,602,173",59,...,"226,333","1,358,000",0,75,0,38,50.7,"52,565","1,997,470",0
19,2022-02-20,Sun,92,0,81,88.0,"175,551","14,219,661","1,861,628",59,...,0,0,0,75,0,0,0.0,0,0,0
20,2022-02-21,Mon,92,0,81,88.0,"184,183","14,918,846","1,612,766",59,...,"80,000","640,000",0,75,0,0,0.0,0,0,0

In [43]:
data2022 = data[data['Date']!= 'Total']
data2022

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2022-01-01,Sat,91,1,75,82.4,"254,748","19,106,127","2,039,406",59,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-01-02,Sun,92,0,57,62.0,"178,332","10,164,911","1,238,268",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-01-03,Mon,92,0,61,66.3,"163,256","9,958,637","1,038,132",54,...,0,0,0,75,0,0,0.0,0,0,0
3,2022-01-04,Tue,92,0,57,62.0,"156,772","8,936,010","1,419,221",56,...,0,0,0,75,0,0,0.0,0,0,0
4,2022-01-05,Wed,92,0,61,66.3,"161,997","9,881,790","1,379,541",56,...,0,0,0,75,0,0,0.0,0,0,0
5,2022-01-06,Thu,92,0,66,71.7,"171,070","11,290,647","1,530,542",58,...,0,0,0,75,0,0,0.0,0,0,0
6,2022-01-07,Fri,92,0,68,73.9,"196,679","13,374,199","1,654,766",57,...,0,0,0,75,0,0,0.0,0,0,0
7,2022-01-08,Sat,92,0,69,75.0,"198,507","13,696,957","1,560,266",57,...,"50,000","1,700,000",0,75,0,47,62.7,"64,875","3,049,105",0
8,2022-01-09,Sun,92,0,67,72.8,"185,547","12,431,677","1,691,677",56,...,0,0,0,75,0,0,0.0,0,0,0
9,2022-01-10,Mon,92,0,64,69.6,"178,001","11,392,066","1,543,902",58,...,0,0,0,75,0,0,0.0,0,0,0
10,2022-01-11,Tue,92,0,62,67.4,"171,622","10,640,542","1,471,768",58,...,"600,000","2,400,000",0,75,0,0,0.0,0,"136,545",0
11,2022-01-12,Wed,92,0,72,78.3,"172,053","12,387,851","1,626,088",59,...,0,0,0,75,0,0,0.0,0,0,0
12,2022-01-13,Thu,92,0,74,80.4,"167,794","12,416,740","1,388,585",59,...,0,0,0,75,0,0,0.0,0,0,0
13,2022-01-14,Fri,92,0,67,72.8,"204,640","13,710,907","2,138,992",59,...,"90,000","1,530,000",0,75,0,0,0.0,0,0,0
14,2022-01-15,Sat,92,0,77,83.7,"216,467","16,667,978","2,238,992",59,...,"122,718","4,786,000",0,75,0,41,54.7,"51,761","2,122,199",0
15,2022-01-16,Sun,92,0,69,75.0,"174,344","12,029,728","1,586,586",59,...,0,0,0,75,0,0,0.0,0,0,0
16,2022-01-17,Mon,92,0,83,90.2,"175,810","14,592,248","1,847,721",59,...,0,0,0,75,0,0,0.0,0,0,0
17,2022-01-18,Tue,92,0,83,90.2,"172,662","14,330,976","1,886,403",57,...,0,0,0,75,0,8,10.7,"150,000","1,200,000",0
18,2022-01-19,Wed,92,0,71,77.2,"166,488","11,820,653","1,557,314",58,...,0,0,0,75,0,0,0.0,0,0,0
19,2022-01-20,Thu,92,0,66,71.7,"179,120","11,821,928","1,448,269",57,...,0,0,0,75,0,0,0.0,0,0,0
20,2022-01-21,Fri,92,0,62,67.4,"212,648","13,184,170","1,710,630",56,...,"450,000","900,000",0,75,0,0,0.0,0,0,0
21,2022-01-22,Sat,92,0,67,72.8,"215,081","14,410,395","2,193,857",56,...,"117,368","2,230,000",0,75,0,40,53.3,"52,410","2,096,380",0
22,2022-01-23,Sun,92,0,75,81.5,"167,131","12,534,853","1,747,174",56,...,0,0,0,75,0,0,0.0,0,0,0
23,2022-01-24,Mon,91,0,70,76.9,"172,137","12,049,617","1,733,087",59,...,"100,000","400,000",0,75,0,0,0.0,0,0,0
24,2022-01-25,Tue,92,0,69,75.0,"172,361","11,892,888","1,718,724",57,...,0,0,0,75,0,73,97.3,"46,230","3,374,760",0
25,2022-01-26,Wed,92,0,58,63.0,"168,596","9,778,585","1,326,995",56,...,0,0,0,75,0,71,94.7,"45,680","3,243,305",0
26,2022-01-27,Thu,92,0,67,72.8,"161,864","10,844,920","1,487,131",56,...,0,0,0,75,0,67,89.3,"45,455","3,045,485",0
27,2022-01-28,Fri,92,0,70,76.1,"189,729","13,281,049","1,238,859",56,...,0,0,0,75,0,70,93.3,"43,507","3,045,486",0
28,2022-01-29,Sat,92,0,72,78.3,"242,407","17,453,268","1,363,723",54,...,0,0,0,75,0,67,89.3,"74,709","5,005,485",0
29,2022-01-30,Sun,92,0,81,88.0,"285,609","23,134,309","1,808,448",53,...,"700,000","2,100,000",0,75,0,0,0.0,0,0,0
30,2022-01-31,Mon,91,1,82,90.1,"286,506","23,493,466","2,490,540",53,...,0,0,0,75,0,0,0.0,0,0,0
0,2022-02-01,Tue,92,0,68,73.9,"246,284","16,747,307","1,538,222",58,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-02-02,Wed,92,0,66,71.7,"196,848","12,991,941","1,386,540",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-02-03,Thu,92,0,77,83.7,"206,959","15,935,842","1,243,858",58,...,0,0,0,75,0,23,30.7,"55,305","1,272,009",0
3,2022-02-04,Fri,92,0,74,80.4,"196,055","14,508,091","1,716,402",59,...,0,0,0,75,0,37,49.3,"164,364","6,081,461",0
4,2022-02-05,Sat,92,0,75,81.5,"188,665","14,149,912","1,563,675",59,...,"91,629","3,207,000",0,75,0,29,38.7,"73,348","2,127,103",0
5,2022-02-06,Sun,91,1,59,64.8,"174,951","10,322,080","1,422,951",59,...,0,0,0,75,0,8,10.7,"110,364","882,912",0
6,2022-02-07,Mon,91,1,66,72.5,"179,314","11,834,730","1,673,448",59,...,"79,000","316,000",0,75,0,0,0.0,0,0,0
7,2022-02-08,Tue,92,0,60,65.2,"172,458","10,347,467","1,492,675",59,...,0,0,0,75,0,13,17.3,"52,182","678,369",0
8,2022-02-09,Wed,92,0,59,64.1,"168,592","9,946,929","1,230,130",59,...,0,0,0,75,0,0,0.0,0,"680,000",0
9,2022-02-10,Thu,92,0,59,64.1,"172,641","10,185,827","1,355,632",58,...,0,0,0,75,0,12,16.0,"100,000","1,200,000",0
10,2022-02-11,Fri,92,0,76,82.6,"200,052","15,203,914","1,811,630",57,...,"190,429","1,333,000",0,75,0,52,69.3,"100,000","5,200,000",0
11,2022-02-12,Sat,92,0,73,79.3,"205,803","15,023,647","1,818,947",59,...,"122,333","1,835,000",0,75,0,32,42.7,"102,353","3,275,282",0
12,2022-02-13,Sun,92,0,61,66.3,"179,520","10,950,690","1,144,494",59,...,0,0,0,75,0,0,0.0,0,0,0
13,2022-02-14,Mon,92,0,63,68.5,"177,834","11,203,554","1,471,220",58,...,"79,000","474,000",0,75,0,16,21.3,"100,000","1,600,000",0
14,2022-02-15,Tue,92,0,73,79.3,"167,643","12,237,906","1,529,833",59,...,0,0,0,75,0,0,0.0,0,0,0
15,2022-02-16,Wed,92,0,79,85.9,"176,436","13,938,440","1,820,719",59,...,0,0,0,75,0,0,0.0,0,0,0
16,2022-02-17,Thu,92,0,77,83.7,"181,530","13,977,772","1,927,629",59,...,0,0,0,75,0,0,0.0,0,0,0
17,2022-02-18,Fri,92,0,82,89.1,"199,937","16,394,814","1,998,493",59,...,0,0,0,75,0,0,0.0,0,0,0
18,2022-02-19,Sat,92,0,87,94.6,"195,250","16,986,738","1,602,173",59,...,"226,333","1,358,000",0,75,0,38,50.7,"52,565","1,997,470",0
19,2022-02-20,Sun,92,0,81,88.0,"175,551","14,219,661","1,861,628",59,...,0,0,0,75,0,0,0.0,0,0,0
20,2022-02-21,Mon,92,0,81,88.0,"184,183","14,918,846","1,612,766",59,...,"80,000","640,000",0,75,0,0,0.0,0,0,0

## ----------------------------------------------------------------------------------------------------

In [44]:
Total = pd.concat([data2003, data_past, data2021, data2022])
Total

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,2022-02-17,Thu,92.0,0.0,77.0,83.7,"181,530","13,977,772","1,927,629",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
17,2022-02-18,Fri,92.0,0.0,82.0,89.1,"199,937","16,394,814","1,998,493",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
18,2022-02-19,Sat,92.0,0.0,87.0,94.6,"195,250","16,986,738","1,602,173",59.0,...,"226,333","1,358,000",0,75.0,0.0,38.0,50.7,"52,565","1,997,470",0
19,2022-02-20,Sun,92.0,0.0,81.0,88.0,"175,551","14,219,661","1,861,628",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
20,2022-02-21,Mon,92.0,0.0,81.0,88.0,"184,183","14,918,846","1,612,766",59.0,...,"80,000","640,000",0,75.0,0.0,0.0,0.0,0,0,0

In [45]:
df = Total.copy()
df.index = df['Date']

In [46]:
#객실운영률 최대 67%로 제한
df['2020-12-18':'2021-02-14'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-18,2020-12-18,Fri,91.0,1.0,29.0,31.9,"172,961","5,015,867","434,725",57.0,...,0,0,0,75.0,0.0,35.0,46.7,"76,527","2,678,445",0
2020-12-19,2020-12-19,Sat,91.0,1.0,40.0,44.0,"169,553","6,782,124","521,178",56.0,...,"266,667","800,000",0,75.0,0.0,35.0,46.7,"76,527","2,678,445",0
2020-12-20,2020-12-20,Sun,92.0,0.0,35.0,38.0,"131,999","4,619,962","659,907",58.0,...,0,0,0,75.0,0.0,35.0,46.7,"76,527","2,678,445",0

In [47]:
#객실운영률 최대 75%로 제한
df['2021-07-19':'2021-08-17'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-19,2021-07-19,Mon,91.0,1.0,67.0,73.6,"211,252","14,153,903","1,319,086",59.0,...,0,0,0,75.0,0.0,75.0,100.0,"47,273","3,545,475",0
2021-07-20,2021-07-20,Tue,91.0,1.0,67.0,73.6,"205,409","13,762,372","1,045,179",58.0,...,"47,273","2,127,285",0,75.0,0.0,75.0,100.0,"47,273","3,545,475",0
2021-07-21,2021-07-21,Wed,92.0,0.0,67.0,72.8,"208,663","13,980,390","790,589",59.0,...,"47,273","2,127,285",0,75.0,0.0,75.0,100.0,"47,273","3,545,475",0

In [48]:
#객실운영률 최대 67%로 제한
df['2021-08-18':'2021-09-22'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2021-08-18,2021-08-18,Wed,92.0,0.0,58.0,63.0,"238,909","13,856,741","1,138,406",57.0,...,"47,273","1,607,282",0,75.0,0.0,70.0,93.3,"49,091","3,436,370",0
2021-08-19,2021-08-19,Thu,92.0,0.0,46.0,50.0,"232,591","10,699,175","826,226",58.0,...,"47,273","1,607,282",0,75.0,0.0,70.0,93.3,"49,091","3,436,370",0
2021-08-20,2021-08-20,Fri,92.0,0.0,52.0,56.5,"244,162","12,696,430","623,771",58.0,...,0,0,0,75.0,0.0,70.0,93.3,"49,091","3,436,370",0

In [49]:
#객실운영률 최대 75%로 제한
df['2021-09-23':'2021-10-17'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2021-09-23,2021-09-23,Thu,92.0,0.0,67.0,72.8,"195,325","13,086,799","1,024,180",59.0,...,0,0,0,75.0,0.0,20.0,26.7,"49,091","981,820",0
2021-09-24,2021-09-24,Fri,92.0,0.0,67.0,72.8,"218,953","14,669,823","1,437,543",58.0,...,0,0,0,75.0,0.0,20.0,26.7,"49,091","981,820",0
2021-09-25,2021-09-25,Sat,92.0,0.0,65.0,70.7,"215,867","14,031,354","1,073,181",59.0,...,0,0,0,75.0,0.0,20.0,26.7,"49,091","981,820",0

In [50]:
def scale67(x):
    return (x*100)/67

In [51]:
def scale75(x):
    return (x*100)/75

In [52]:
df.loc['2020-12-18':'2021-02-14', '제주Occ%'] = round(df['2020-12-18':'2021-02-14']['제주Occ%'].apply(scale67),1)
df.loc['2021-07-19':'2021-08-17', '제주Occ%'] = round(df['2021-07-19':'2021-08-17']['제주Occ%'].apply(scale75),1)
df.loc['2021-08-18':'2021-09-22', '제주Occ%'] = round(df['2021-08-18':'2021-09-22']['제주Occ%'].apply(scale67),1)
df.loc['2021-09-23':'2021-10-17', '제주Occ%'] = round(df['2021-09-23':'2021-10-17']['제주Occ%'].apply(scale75),1)

In [53]:
df.to_excel('data(2003.7_2022.02.21).xlsx', header = True, index=False)