In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from fbprophet import Prophet

In [2]:
yy = ['2003']
mm = ['07','08','09','10','11','12']

In [3]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [4]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [6]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [7]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [8]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [9]:
data.columns = new_col

In [10]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2003-12-28,Sun,89.0,1.0,46.0,51.7,"107,272","4,934,493",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2003-12-29,Mon,85.0,5.0,66.0,77.6,"84,144","5,553,508",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2003-12-30,Tue,89.0,1.0,58.0,65.2,"84,436","4,897,312",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2003-12-31,Wed,89.0,1.0,80.0,89.9,"100,984","8,078,751",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Total,,2745.0,45.0,1230.0,44.8,88670,109064087,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
data2003 = data[data['Date']!= 'Total']
data2003

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2003-12-27,Sat,88.0,2.0,56.0,63.6,"83,378","4,669,144",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2003-12-28,Sun,89.0,1.0,46.0,51.7,"107,272","4,934,493",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2003-12-29,Mon,85.0,5.0,66.0,77.6,"84,144","5,553,508",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2003-12-30,Tue,89.0,1.0,58.0,65.2,"84,436","4,897,312",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2003-12-31,Wed,89.0,1.0,80.0,89.9,"100,984","8,078,751",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ----------------------------------------------------------------------------------------------------

In [12]:
yy = ['2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020']
mm = ['01','02','03','04','05','06','07','08','09','10','11','12']

In [13]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [14]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2004-01-01,Thu,89,1,68,76.4,"114,383","7,778,018",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-02,Fri,89,1,79,88.8,"119,379","9,430,924",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-03,Sat,89,1,55,61.8,"111,780","6,147,881",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-04,Sun,89,1,45,50.6,"102,855","4,628,476",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-05,Mon,89,1,43,48.3,"77,579","3,335,906",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [16]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [17]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [18]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [19]:
data.columns = new_col

In [20]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2004-01-01,Thu,89,1,68,76.4,"114,383","7,778,018",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-02,Fri,89,1,79,88.8,"119,379","9,430,924",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-03,Sat,89,1,55,61.8,"111,780","6,147,881",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-04,Sun,89,1,45,50.6,"102,855","4,628,476",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-05,Mon,89,1,43,48.3,"77,579","3,335,906",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2020-12-28,Mon,92,0,27,29.3,"153,094","4,133,542","460,544",46.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
28,2020-12-29,Tue,92,0,23,25.0,"164,784","3,790,030","180,181",37.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
29,2020-12-30,Wed,92,0,20,21.7,"193,526","3,870,529","268,226",47.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
30,2020-12-31,Thu,92,0,24,26.1,"213,515","5,124,361","648,634",50.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
31,Total,,2850,2,1135,39.8,154309,175141026,20999995,1740.0,...,114269,7656000,0,2325.0,0.0,1220.0,52.5,122945,149993100,0

In [21]:
data_past = data[data['Date']!= 'Total']
data_past

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2004-01-01,Thu,89,1,68,76.4,"114,383","7,778,018",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-02,Fri,89,1,79,88.8,"119,379","9,430,924",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-03,Sat,89,1,55,61.8,"111,780","6,147,881",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-04,Sun,89,1,45,50.6,"102,855","4,628,476",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-05,Mon,89,1,43,48.3,"77,579","3,335,906",0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2020-12-27,Sun,92,0,25,27.2,"153,063","3,826,575","705,816",51.0,...,0,"232,000",0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
27,2020-12-28,Mon,92,0,27,29.3,"153,094","4,133,542","460,544",46.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
28,2020-12-29,Tue,92,0,23,25.0,"164,784","3,790,030","180,181",37.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
29,2020-12-30,Wed,92,0,20,21.7,"193,526","3,870,529","268,226",47.0,...,0,0,0,75.0,0.0,75.0,100.0,"202,372","15,177,885",0
30,2020-12-31,Thu,92,0,24,26.1,"213,515","5,124,361","648,634",50.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0

## ----------------------------------------------------------------------------------------------------

In [22]:
yy = ['2021']
mm = ['01','02','03','04','05','06','07','08','09','10','11','12']

In [23]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [24]:
data = data.loc[:, :'FB Rev..6']

In [25]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2021-01-01,Fri,92,0,27,29.3,"223,941","6,046,409","797,996",49,...,0,0,0,75,0,0,0.0,0,0,0
1,2021-01-02,Sat,92,0,25,27.2,"195,915","4,897,872","690,224",56,...,0,0,0,75,0,0,0.0,0,0,0
2,2021-01-03,Sun,92,0,15,16.3,"145,439","2,181,590","339,953",57,...,0,0,0,75,0,0,0.0,0,0,0
3,2021-01-04,Mon,92,0,4,4.3,"171,741","686,964","74,727",55,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
4,2021-01-05,Tue,92,0,13,14.1,"130,035","1,690,454","205,639",56,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0

In [26]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [27]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [28]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [29]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [30]:
data.columns = new_col

In [31]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2021-01-01,Fri,92,0,27,29.3,"223,941","6,046,409","797,996",49,...,0,0,0,75,0,0,0.0,0,0,0
1,2021-01-02,Sat,92,0,25,27.2,"195,915","4,897,872","690,224",56,...,0,0,0,75,0,0,0.0,0,0,0
2,2021-01-03,Sun,92,0,15,16.3,"145,439","2,181,590","339,953",57,...,0,0,0,75,0,0,0.0,0,0,0
3,2021-01-04,Mon,92,0,4,4.3,"171,741","686,964","74,727",55,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
4,2021-01-05,Tue,92,0,13,14.1,"130,035","1,690,454","205,639",56,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2021-12-28,Tue,92,0,80,87.0,"186,346","14,907,652","1,820,130",59,...,0,0,0,75,0,0,0.0,0,"-1,276,364",0
28,2021-12-29,Wed,92,0,70,76.1,"187,618","13,133,251","1,546,357",59,...,0,0,0,75,0,0,0.0,0,0,0
29,2021-12-30,Thu,92,0,76,82.6,"215,450","16,374,173","1,657,450",59,...,0,0,0,75,0,0,0.0,0,0,0
30,2021-12-31,Fri,91,1,81,89.0,"295,308","23,919,912","1,808,406",59,...,0,0,0,75,0,0,0.0,0,0,0
31,Total,,2842,7,2226,78.3,191813,426975887,42986096,1785,...,53889,1455000,0,2325,0,576,24.8,47898,27589143,0

In [32]:
data2021 = data[data['Date']!= 'Total']
data2021

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2021-01-01,Fri,92,0,27,29.3,"223,941","6,046,409","797,996",49,...,0,0,0,75,0,0,0.0,0,0,0
1,2021-01-02,Sat,92,0,25,27.2,"195,915","4,897,872","690,224",56,...,0,0,0,75,0,0,0.0,0,0,0
2,2021-01-03,Sun,92,0,15,16.3,"145,439","2,181,590","339,953",57,...,0,0,0,75,0,0,0.0,0,0,0
3,2021-01-04,Mon,92,0,4,4.3,"171,741","686,964","74,727",55,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
4,2021-01-05,Tue,92,0,13,14.1,"130,035","1,690,454","205,639",56,...,0,0,0,75,0,35,46.7,"63,636","2,227,260",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2021-12-27,Mon,90,0,72,80.0,"187,317","13,486,841","1,623,721",59,...,0,0,0,75,0,0,0.0,0,0,0
27,2021-12-28,Tue,92,0,80,87.0,"186,346","14,907,652","1,820,130",59,...,0,0,0,75,0,0,0.0,0,"-1,276,364",0
28,2021-12-29,Wed,92,0,70,76.1,"187,618","13,133,251","1,546,357",59,...,0,0,0,75,0,0,0.0,0,0,0
29,2021-12-30,Thu,92,0,76,82.6,"215,450","16,374,173","1,657,450",59,...,0,0,0,75,0,0,0.0,0,0,0
30,2021-12-31,Fri,91,1,81,89.0,"295,308","23,919,912","1,808,406",59,...,0,0,0,75,0,0,0.0,0,0,0

## ----------------------------------------------------------------------------------------------------

In [33]:
yy = ['2022']
mm = ['01','02','03']

In [34]:
path = 'data/'
data = pd.DataFrame()

for i in yy:
      for j in mm:
            table = pd.read_excel(path + i + '_' + j+'.xls', header = 1)
            data = pd.concat([data,table])

In [35]:
data = data.loc[:, :'FB Rev..6']

In [36]:
data.head()

,Unnamed: 0,Unnamed: 1,Ava,H/U,Sold,Occ%,ADR,Rm Rev.,FB Rev.,Ava.1,...,ADR.5,Rm Rev..5,FB Rev..5,Ava.6,H/U.6,Sold.6,Occ%.6,ADR.6,Rm Rev..6,FB Rev..6
0,2022-01-01,Sat,91,1,75,82.4,"254,748","19,106,127","2,039,406",59,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-01-02,Sun,92,0,57,62.0,"178,332","10,164,911","1,238,268",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-01-03,Mon,92,0,61,66.3,"163,256","9,958,637","1,038,132",54,...,0,0,0,75,0,0,0.0,0,0,0
3,2022-01-04,Tue,92,0,57,62.0,"156,772","8,936,010","1,419,221",56,...,0,0,0,75,0,0,0.0,0,0,0
4,2022-01-05,Wed,92,0,61,66.3,"161,997","9,881,790","1,379,541",56,...,0,0,0,75,0,0,0.0,0,0,0

In [37]:
hotel = ['제주','남원','경주','낙산','드림','도고','가평']
col = data.columns

In [38]:
col

Index(['Unnamed: 0', 'Unnamed: 1', 'Ava', 'H/U', 'Sold', 'Occ%', 'ADR',
       'Rm Rev.', 'FB Rev.', 'Ava.1', 'H/U.1', 'Sold.1', 'Occ%.1', 'ADR.1',
       'Rm Rev..1', 'FB Rev..1', 'Ava.2', 'H/U.2', 'Sold.2', 'Occ%.2', 'ADR.2',
       'Rm Rev..2', 'FB Rev..2', 'Ava.3', 'H/U.3', 'Sold.3', 'Occ%.3', 'ADR.3',
       'Rm Rev..3', 'FB Rev..3', 'Ava.4', 'H/U.4', 'Sold.4', 'Occ%.4', 'ADR.4',
       'Rm Rev..4', 'FB Rev..4', 'Ava.5', 'H/U.5', 'Sold.5', 'Occ%.5', 'ADR.5',
       'Rm Rev..5', 'FB Rev..5', 'Ava.6', 'H/U.6', 'Sold.6', 'Occ%.6', 'ADR.6',
       'Rm Rev..6', 'FB Rev..6'],
      dtype='object')

In [39]:
new_col = ['Date','Day']
for i in hotel:
      for j in range(2, 9):
            ncol = i + col[j]
            new_col.append(ncol)

In [40]:
new_col

['Date',
 'Day',
 '제주Ava',
 '제주H/U',
 '제주Sold',
 '제주Occ%',
 '제주ADR',
 '제주Rm Rev.',
 '제주FB Rev.',
 '남원Ava',
 '남원H/U',
 '남원Sold',
 '남원Occ%',
 '남원ADR',
 '남원Rm Rev.',
 '남원FB Rev.',
 '경주Ava',
 '경주H/U',
 '경주Sold',
 '경주Occ%',
 '경주ADR',
 '경주Rm Rev.',
 '경주FB Rev.',
 '낙산Ava',
 '낙산H/U',
 '낙산Sold',
 '낙산Occ%',
 '낙산ADR',
 '낙산Rm Rev.',
 '낙산FB Rev.',
 '드림Ava',
 '드림H/U',
 '드림Sold',
 '드림Occ%',
 '드림ADR',
 '드림Rm Rev.',
 '드림FB Rev.',
 '도고Ava',
 '도고H/U',
 '도고Sold',
 '도고Occ%',
 '도고ADR',
 '도고Rm Rev.',
 '도고FB Rev.',
 '가평Ava',
 '가평H/U',
 '가평Sold',
 '가평Occ%',
 '가평ADR',
 '가평Rm Rev.',
 '가평FB Rev.']

In [41]:
data.columns = new_col

In [42]:
data

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2022-01-01,Sat,91,1,75,82.4,"254,748","19,106,127","2,039,406",59,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-01-02,Sun,92,0,57,62.0,"178,332","10,164,911","1,238,268",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-01-03,Mon,92,0,61,66.3,"163,256","9,958,637","1,038,132",54,...,0,0,0,75,0,0,0.0,0,0,0
3,2022-01-04,Tue,92,0,57,62.0,"156,772","8,936,010","1,419,221",56,...,0,0,0,75,0,0,0.0,0,0,0
4,2022-01-05,Wed,92,0,61,66.3,"161,997","9,881,790","1,379,541",56,...,0,0,0,75,0,0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2022-03-28,Mon,90,2,66,73.3,"183,577","12,116,049","1,256,539",59,...,0,0,0,75,0,0,0.0,0,0,0
28,2022-03-29,Tue,90,0,75,83.3,"164,714","12,353,525","1,514,994",59,...,0,"-95,000",0,75,0,6,8.0,"90,000","540,000","1,104,000"
29,2022-03-30,Wed,92,0,58,63.0,"167,649","9,723,620","1,093,860",59,...,0,0,0,75,0,0,0.0,0,0,0
30,2022-03-31,Thu,92,0,58,63.0,"179,144","10,390,373","880,633",59,...,0,0,0,75,0,0,0.0,0,0,0
31,Total,,2831,19,1853,65.5,174810,323923169,35954196,1802,...,99380,13615000,0,2325,0,183,7.9,91164,16683094,1104000

In [43]:
data2022 = data[data['Date']!= 'Total']
data2022

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2022-01-01,Sat,91,1,75,82.4,"254,748","19,106,127","2,039,406",59,...,0,0,0,75,0,0,0.0,0,0,0
1,2022-01-02,Sun,92,0,57,62.0,"178,332","10,164,911","1,238,268",58,...,0,0,0,75,0,0,0.0,0,0,0
2,2022-01-03,Mon,92,0,61,66.3,"163,256","9,958,637","1,038,132",54,...,0,0,0,75,0,0,0.0,0,0,0
3,2022-01-04,Tue,92,0,57,62.0,"156,772","8,936,010","1,419,221",56,...,0,0,0,75,0,0,0.0,0,0,0
4,2022-01-05,Wed,92,0,61,66.3,"161,997","9,881,790","1,379,541",56,...,0,0,0,75,0,0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2022-03-27,Sun,92,0,67,72.8,"185,019","12,396,297","1,195,450",59,...,0,0,0,75,0,0,0.0,0,0,0
27,2022-03-28,Mon,90,2,66,73.3,"183,577","12,116,049","1,256,539",59,...,0,0,0,75,0,0,0.0,0,0,0
28,2022-03-29,Tue,90,0,75,83.3,"164,714","12,353,525","1,514,994",59,...,0,"-95,000",0,75,0,6,8.0,"90,000","540,000","1,104,000"
29,2022-03-30,Wed,92,0,58,63.0,"167,649","9,723,620","1,093,860",59,...,0,0,0,75,0,0,0.0,0,0,0
30,2022-03-31,Thu,92,0,58,63.0,"179,144","10,390,373","880,633",59,...,0,0,0,75,0,0,0.0,0,0,0

## ----------------------------------------------------------------------------------------------------

In [44]:
Total = pd.concat([data2003, data_past, data2021, data2022])
Total

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
0,2003-07-01,Tue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003-07-02,Wed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003-07-03,Thu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003-07-04,Fri,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003-07-05,Sat,0.0,0.0,0.0,0.0,0,"110,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2022-03-27,Sun,92.0,0.0,67.0,72.8,"185,019","12,396,297","1,195,450",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
27,2022-03-28,Mon,90.0,2.0,66.0,73.3,"183,577","12,116,049","1,256,539",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
28,2022-03-29,Tue,90.0,0.0,75.0,83.3,"164,714","12,353,525","1,514,994",59.0,...,0,"-95,000",0,75.0,0.0,6.0,8.0,"90,000","540,000","1,104,000"
29,2022-03-30,Wed,92.0,0.0,58.0,63.0,"167,649","9,723,620","1,093,860",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
30,2022-03-31,Thu,92.0,0.0,58.0,63.0,"179,144","10,390,373","880,633",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0

In [45]:
df = Total.copy()
df.index = df['Date']

In [46]:
#객실운영률 최대 67%로 제한
df['2020-12-18':'2021-02-14'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-18,2020-12-18,Fri,91.0,1.0,29.0,31.9,"172,961","5,015,867","434,725",57.0,...,0,0,0,75.0,0.0,35.0,46.7,"76,527","2,678,445",0
2020-12-19,2020-12-19,Sat,91.0,1.0,40.0,44.0,"169,553","6,782,124","521,178",56.0,...,"266,667","800,000",0,75.0,0.0,35.0,46.7,"76,527","2,678,445",0
2020-12-20,2020-12-20,Sun,92.0,0.0,35.0,38.0,"131,999","4,619,962","659,907",58.0,...,0,0,0,75.0,0.0,35.0,46.7,"76,527","2,678,445",0

In [47]:
#객실운영률 최대 75%로 제한
df['2021-07-19':'2021-08-17'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-19,2021-07-19,Mon,91.0,1.0,67.0,73.6,"211,252","14,153,903","1,319,086",59.0,...,0,0,0,75.0,0.0,75.0,100.0,"47,273","3,545,475",0
2021-07-20,2021-07-20,Tue,91.0,1.0,67.0,73.6,"205,409","13,762,372","1,045,179",58.0,...,"47,273","2,127,285",0,75.0,0.0,75.0,100.0,"47,273","3,545,475",0
2021-07-21,2021-07-21,Wed,92.0,0.0,67.0,72.8,"208,663","13,980,390","790,589",59.0,...,"47,273","2,127,285",0,75.0,0.0,75.0,100.0,"47,273","3,545,475",0

In [48]:
#객실운영률 최대 67%로 제한
df['2021-08-18':'2021-09-22'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2021-08-18,2021-08-18,Wed,92.0,0.0,58.0,63.0,"238,909","13,856,741","1,138,406",57.0,...,"47,273","1,607,282",0,75.0,0.0,70.0,93.3,"49,091","3,436,370",0
2021-08-19,2021-08-19,Thu,92.0,0.0,46.0,50.0,"232,591","10,699,175","826,226",58.0,...,"47,273","1,607,282",0,75.0,0.0,70.0,93.3,"49,091","3,436,370",0
2021-08-20,2021-08-20,Fri,92.0,0.0,52.0,56.5,"244,162","12,696,430","623,771",58.0,...,0,0,0,75.0,0.0,70.0,93.3,"49,091","3,436,370",0

In [49]:
#객실운영률 최대 75%로 제한
df['2021-09-23':'2021-10-17'].head(3)

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2021-09-23,2021-09-23,Thu,92.0,0.0,67.0,72.8,"195,325","13,086,799","1,024,180",59.0,...,0,0,0,75.0,0.0,20.0,26.7,"49,091","981,820",0
2021-09-24,2021-09-24,Fri,92.0,0.0,67.0,72.8,"218,953","14,669,823","1,437,543",58.0,...,0,0,0,75.0,0.0,20.0,26.7,"49,091","981,820",0
2021-09-25,2021-09-25,Sat,92.0,0.0,65.0,70.7,"215,867","14,031,354","1,073,181",59.0,...,0,0,0,75.0,0.0,20.0,26.7,"49,091","981,820",0

In [50]:
def scale67(x):
    return (x*100)/67

In [51]:
def scale75(x):
    return (x*100)/75

In [52]:
df.loc['2020-12-18':'2021-02-14', '제주Occ%'] = round(df['2020-12-18':'2021-02-14']['제주Occ%'].apply(scale67),1)
df.loc['2021-07-19':'2021-08-17', '제주Occ%'] = round(df['2021-07-19':'2021-08-17']['제주Occ%'].apply(scale75),1)
df.loc['2021-08-18':'2021-09-22', '제주Occ%'] = round(df['2021-08-18':'2021-09-22']['제주Occ%'].apply(scale67),1)
df.loc['2021-09-23':'2021-10-17', '제주Occ%'] = round(df['2021-09-23':'2021-10-17']['제주Occ%'].apply(scale75),1)

In [53]:
data = df

In [54]:
#2003년 7월 15일 이후 최종예약률을 활용
data = data.iloc[14:,]

In [55]:
data.head()

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2003-07-15,2003-07-15,Tue,88.0,2.0,69.0,78.4,"95,652","6,600,000",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-07-16,2003-07-16,Wed,88.0,2.0,72.0,81.8,"99,901","7,192,902",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-07-17,2003-07-17,Thu,86.0,4.0,35.0,40.7,"81,647","2,857,629",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-07-18,2003-07-18,Fri,85.0,5.0,41.0,48.2,"75,187","3,082,654",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-07-19,2003-07-19,Sat,88.0,2.0,28.0,31.8,"146,477","4,101,355",0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
data.tail()

,Date,Day,제주Ava,제주H/U,제주Sold,제주Occ%,제주ADR,제주Rm Rev.,제주FB Rev.,남원Ava,...,도고ADR,도고Rm Rev.,도고FB Rev.,가평Ava,가평H/U,가평Sold,가평Occ%,가평ADR,가평Rm Rev.,가평FB Rev.
Date,,,,,,,,,,,,,,,,,,,,,
2022-03-27,2022-03-27,Sun,92.0,0.0,67.0,72.8,"185,019","12,396,297","1,195,450",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
2022-03-28,2022-03-28,Mon,90.0,2.0,66.0,73.3,"183,577","12,116,049","1,256,539",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
2022-03-29,2022-03-29,Tue,90.0,0.0,75.0,83.3,"164,714","12,353,525","1,514,994",59.0,...,0,"-95,000",0,75.0,0.0,6.0,8.0,"90,000","540,000","1,104,000"
2022-03-30,2022-03-30,Wed,92.0,0.0,58.0,63.0,"167,649","9,723,620","1,093,860",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0
2022-03-31,2022-03-31,Thu,92.0,0.0,58.0,63.0,"179,144","10,390,373","880,633",59.0,...,0,0,0,75.0,0.0,0.0,0.0,0,0,0

In [57]:
data['Date'] = pd.to_datetime(data['Date'])

C:\Users\Owner\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6835 entries, 2003-07-15 to 2022-03-31
Data columns (total 51 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6835 non-null   datetime64[ns]
 1   Day        6835 non-null   object
 2   제주Ava      6835 non-null   float64
 3   제주H/U      6835 non-null   float64
 4   제주Sold     6835 non-null   float64
 5   제주Occ%     6835 non-null   float64
 6   제주ADR      6835 non-null   object
 7   제주Rm Rev.  6835 non-null   object
 8   제주FB Rev.  6835 non-null   object
 9   남원Ava      3676 non-null   float64
 10  남원H/U      3676 non-null   float64
 11  남원Sold     3676 non-null   float64
 12  남원Occ%     3676 non-null   float64
 13  남원ADR      3676 non-null   object
 14  남원Rm Rev.  3676 non-null   object
 15  남원FB Rev.  3676 non-null   object
 16  경주Ava      5070 non-null   float64
 17  경주H/U      5070 non-null   float64
 18  경주Sold     5070 non-null   float64
 19  경주Occ%     5070 non-null   float64
 20  경주ADR      5070 non-null   object
 21  경주Rm Rev.  5070 non-null   object
 22  경주FB Rev.  5070 non-null   object
 23  낙산Ava      5628 non-null   float64
 24  낙산H/U      5628 non-null   float64
 25  낙산Sold     5628 non-null   float64
 26  낙산Occ%     5628 non-null   float64
 27  낙산ADR      5628 non-null   object
 28  낙산Rm Rev.  5628 non-null   object
 29  낙산FB Rev.  5628 non-null   object
 30  드림Ava      5747 non-null   float64
 31  드림H/U      5747 non-null   float64
 32  드림Sold     5747 non-null   float64
 33  드림Occ%     5747 non-null   float64
 34  드림ADR      5747 non-null   object
 35  드림Rm Rev.  5747 non-null   object
 36  드림FB Rev.  5747 non-null   object
 37  도고Ava      3087 non-null   float64
 38  도고H/U      3087 non-null   float64
 39  도고Sold     3087 non-null   float64
 40  도고Occ%     3087 non-null   float64
 41  도고ADR      3087 non-null   object
 42  도고Rm Rev.  3087 non-null   object
 43  도고FB Rev.  3087 non-null   object
 44  가평Ava      3388 non-null   float64
 45  가평H/U      3388 non-null   float64
 46  가평Sold     3388 non-null   float64
 47  가평Occ%     3388 non-null   float64
 48  가평ADR      3388 non-null   object
 49  가평Rm Rev.  3388 non-null   object
 50  가평FB Rev.  3388 non-null   object
dtypes: datetime64[ns](1), float64(28), object(22)
memory usage: 2.7+ MB

In [59]:
data.describe()

,제주Ava,제주H/U,제주Sold,제주Occ%,남원Ava,남원H/U,남원Sold,남원Occ%,경주Ava,경주H/U,...,드림Sold,드림Occ%,도고Ava,도고H/U,도고Sold,도고Occ%,가평Ava,가평H/U,가평Sold,가평Occ%
count,6835.000000,6835.000000,6835.000000,6835.000000,3676.000000,3676.000000,3676.000000,3676.000000,5070.000000,5070.000000,...,5747.000000,5747.000000,3087.000000,3087.000000,3087.000000,3087.000000,3388.000000,3388.000000,3388.000000,3388.000000
mean,89.123336,0.378639,69.795465,78.789568,54.012514,0.836235,31.122144,54.001959,33.548521,0.257791,...,42.814512,45.190882,32.898607,0.914804,6.502753,12.616780,42.267414,0.368359,10.944805,14.791529
std,5.885915,0.778336,20.194127,21.751200,14.084443,3.117535,19.698546,33.698205,2.079955,1.764273,...,32.235100,33.778777,25.746365,4.125800,12.884825,24.805949,36.946221,2.931271,20.104221,27.105290
min,28.000000,0.000000,0.000000,0.000000,-6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,89.000000,0.000000,56.000000,65.200000,58.000000,0.000000,13.000000,23.700000,34.000000,0.000000,...,12.000000,12.450000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,90.000000,0.000000,77.000000,86.900000,58.000000,0.000000,31.000000,55.200000,34.000000,0.000000,...,40.000000,42.700000,54.000000,0.000000,0.000000,0.000000,75.000000,0.000000,0.000000,0.000000
75%,90.000000,1.000000,87.000000,96.700000,59.000000,1.000000,51.000000,87.900000,34.000000,0.000000,...,72.000000,76.300000,54.000000,0.000000,5.000000,9.300000,75.000000,0.000000,14.000000,18.700000
max,92.000000,12.000000,92.000000,104.800000,59.000000,65.000000,59.000000,133.300000,34.000000,34.000000,...,106.000000,120.000000,54.000000,48.000000,54.000000,100.000000,75.000000,53.000000,152.000000,202.700000

In [60]:
df = data[['Date', '제주Occ%']]

In [61]:
df.columns = ['ds', 'y']

In [62]:
df

                   ds     y
Date
2003-07-15 2003-07-15  78.4
2003-07-16 2003-07-16  81.8
2003-07-17 2003-07-17  40.7
2003-07-18 2003-07-18  48.2
2003-07-19 2003-07-19  31.8
...               ...   ...
2022-03-27 2022-03-27  72.8
2022-03-28 2022-03-28  73.3
2022-03-29 2022-03-29  83.3
2022-03-30 2022-03-30  63.0
2022-03-31 2022-03-31  63.0

[6835 rows x 2 columns]

In [63]:
df = df.copy()
df['y'] = np.where(df['y']>100, 100, df['y'])

In [64]:
model = Prophet()
#model = Prophet(yearly_seasonality=True, daily_seasonality=True)

In [65]:
model.fit(df)

INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
C:\Users\Owner\anaconda3\lib\site-packages\pystan\misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):

In [66]:
future = model.make_future_dataframe(periods=60, freq='1D')

In [67]:
pred = model.predict(future)

In [68]:
pred = pred[['ds','yhat','yhat_lower','yhat_upper']]
pred[['ds', 'yhat']].tail()

             ds       yhat
6890 2022-05-26  85.132317
6891 2022-05-27  86.163313
6892 2022-05-28  89.322170
6893 2022-05-29  85.485185
6894 2022-05-30  84.927522

In [69]:
from datetime import datetime
today = datetime.today().strftime("%Y.%m.%d")

pred.to_csv('제주Occ(' + today + '~).csv')